In [5]:
import pandas as pd

In [16]:
import pandas as pd

# Define file paths
file_paths = {
    'parties': r'C:\stasi\SoftUni_DATA_SCIENCE\FINAL_PROJECT\DATA\РЕЗУЛТАТИ ИЗБОРИ 2024\export\Актуализирана база данни - НС\cik_parties_09.06.2024.csv',
    'candidates': r'C:\stasi\SoftUni_DATA_SCIENCE\FINAL_PROJECT\DATA\РЕЗУЛТАТИ ИЗБОРИ 2024\export\Актуализирана база данни - НС\local_candidates_09.06.2024.csv',
    'local_parties': r'C:\stasi\SoftUni_DATA_SCIENCE\FINAL_PROJECT\DATA\РЕЗУЛТАТИ ИЗБОРИ 2024\export\Актуализирана база данни - НС\local_parties_09.06.2024.csv',
    'preferences': r'C:\stasi\SoftUni_DATA_SCIENCE\FINAL_PROJECT\DATA\РЕЗУЛТАТИ ИЗБОРИ 2024\export\Актуализирана база данни - НС\preferences_09.06.2024.csv',
    'protocols': r'C:\stasi\SoftUni_DATA_SCIENCE\FINAL_PROJECT\DATA\РЕЗУЛТАТИ ИЗБОРИ 2024\export\Актуализирана база данни - НС\protocols_09.06.2024.csv',
    'sections': r'C:\stasi\SoftUni_DATA_SCIENCE\FINAL_PROJECT\DATA\РЕЗУЛТАТИ ИЗБОРИ 2024\export\Актуализирана база данни - НС\sections_09.06.2024.csv',
    'votes': r'C:\stasi\SoftUni_DATA_SCIENCE\FINAL_PROJECT\DATA\РЕЗУЛТАТИ ИЗБОРИ 2024\export\Актуализирана база данни - НС\votes_09.06.2024.csv'
}

# Load all datasets with semicolon as delimiter
data_dict = {}
for key, path in file_paths.items():
    try:
        data_dict[key] = pd.read_csv(path, delimiter=';', engine='python', on_bad_lines='skip')
    except pd.errors.ParserError as e:
        print(f"Error loading {key}: {e}")

# Display information about each dataset
for key, df in data_dict.items():
    print(f"\n--- {key.upper()} DATA ---\n")
    print(df.info())
    print(df.head())

--- PARTIES DATA ---

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30 entries, 0 to 29
Data columns (total 2 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   1                   30 non-null     int64
 1   ПП ИМА ТАКЪВ НАРОД  30 non-null     object
dtypes: int64(1), object(1)
memory usage: 612.0+ bytes
None
   1                                 ПП ИМА ТАКЪВ НАРОД
0  2                                    ПП ГЛАС НАРОДЕН
1  3                                      СИНЯ БЪЛГАРИЯ
2  4  НИЕ ГРАЖДАНИТЕ /БЪЛГАРСКАТА ПРОЛЕТ, КОЙ, БРСП,...
3  6                 ПОЛИТИЧЕСКА ПАРТИЯ БЪЛГАРСКИ ГЛАСЪ
4  7                                 КОАЛИЦИЯ НА РОЗАТА

--- CANDIDATES DATA ---

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7603 entries, 0 to 7602
Data columns (total 7 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   1                            7603 non-null   int64
 1   01. БЛАГОЕВГРАД              7603 non-null   object
 2   1.1                          7603 non-null   int64
 3   ПП ИМА ТАКЪВ НАРОД           7603 non-null   object
 4   101                          7603 non-null   int64
 5   Тошко Йорданов Хаджитодоров  7603 non-null   object
 6   Unnamed: 6                   0 non-null      float64
dtypes: float64(1), int64(3), object(3)
memory usage: 415.9+ KB
None
   1  01. БЛАГОЕВГРАД  1.1  ПП ИМА ТАКЪВ НАРОД  101  \
0  1  01. БЛАГОЕВГРАД    1  ПП ИМА ТАКЪВ НАРОД  102
1  1  01. БЛАГОЕВГРАД    1  ПП ИМА ТАКЪВ НАРОД  103
2  1  01. БЛАГОЕВГРАД    1  ПП ИМА ТАКЪВ НАРОД  104
3  1  01. БЛАГОЕВГРАД    1  ПП ИМА ТАКЪВ НАРОД  105
4  1  01. БЛАГОЕВГРАД    1  ПП ИМА ТАКЪВ НАРОД  106

  Тошко Йорданов Хаджитодоров  Unnamed: 6
0  Станислав Иванов Богдански         NaN
1     Иванка Василева Асенова         NaN
2  Миглена Георгиева Думанова         NaN
3  Красимир Георгиев Ангелски         NaN
4         Шериф Янузов Ходжов         NaN

--- LOCAL_PARTIES DATA ---

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 960 entries, 0 to 959
Data columns (total 4 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   1                   960 non-null    int64
 1   01. БЛАГОЕВГРАД     960 non-null    object
 2   1.1                 960 non-null    int64
 3   ПП ИМА ТАКЪВ НАРОД  960 non-null    object
dtypes: int64(2), object(2)
memory usage: 30.1+ KB
None
   1  01. БЛАГОЕВГРАД  1.1                                 ПП ИМА ТАКЪВ НАРОД
0  1  01. БЛАГОЕВГРАД    2                                    ПП ГЛАС НАРОДЕН
1  1  01. БЛАГОЕВГРАД    3                                      СИНЯ БЪЛГАРИЯ
2  1  01. БЛАГОЕВГРАД    4  НИЕ ГРАЖДАНИТЕ /БЪЛГАРСКАТА ПРОЛЕТ, КОЙ, БРСП,...
3  1  01. БЛАГОЕВГРАД    6                 ПОЛИТИЧЕСКА ПАРТИЯ БЪЛГАРСКИ ГЛАСЪ
4  1  01. БЛАГОЕВГРАД    7                                 КОАЛИЦИЯ НА РОЗАТА

--- PREFERENCES DATA ---

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3789569 entries, 0 to 3789568
Data columns (total 7 columns):
 #   Column     Dtype
---  ------     -----
 0   26         int64
 1   010100001  int64
 2   1          int64
 3   Без        object
 4   11         int64
 5   2          int64
 6   9          int64
dtypes: int64(6), object(1)
memory usage: 202.4+ MB
None
   26  010100001  1  Без  11  2  9
0  26   10100001  1  101   3  2  1
1  26   10100001  1  102   1  0  1
2  26   10100001  1  103   0  0  0
3  26   10100001  1  104   4  1  3
4  26   10100001  1  105   1  1  0

--- PROTOCOLS DATA ---

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12975 entries, 0 to 12974
Data columns (total 21 columns):
 #   Column                                                                                                                    Non-Null Count  Dtype
---  ------                                                                                                                    --------------  -----
 0   26                                                                                                                        12975 non-null  int64
 1   010100001                                                                                                                 12975 non-null  int64
 2   1                                                                                                                         12975 non-null  int64
 3   |0110155|0110155|0110155|0110155|0110155|0110155|0110155|0110155|0110155|0110155|0110155|0110155|0110155|0110155|0110155  12975 non-null  object
 4   Unnamed: 4                                                                                                                0 non-null      float64
 5   Unnamed: 5                                                                                                                0 non-null      float64
 6   600                                                                                                                       12975 non-null  int64
 7   608                                                                                                                       12975 non-null  int64
 8   Unnamed: 8                                                                                                                0 non-null      float64
 9   Unnamed: 9                                                                                                                0 non-null      float64
 10  4                                                                                                                         12975 non-null  int64
 11  296                                                                                                                       12975 non-null  int64
 12  450                                                                                                                       12975 non-null  int64
 13  1.1                                                                                                                       12975 non-null  int64
 14  149                                                                                                                       12975 non-null  int64
 15  12                                                                                                                        12975 non-null  int64
 16  3                                                                                                                         12975 non-null  int64
 17  134                                                                                                                       12975 non-null  int64
 18  147                                                                                                                       9600 non-null   float64
 19  7                                                                                                                         9600 non-null   float64
 20  140                                                                                                                       9600 non-null   float64
dtypes: float64(7), int64(13), object(1)
memory usage: 2.1+ MB
None
   26  010100001  1  \
0  26   10100002  1
1  26   10100003  1
2  26   10100004  1
3  26   10100005  1
4  26   10100006  1

  |0110155|0110155|0110155|0110155|0110155|0110155|0110155|0110155|0110155|0110155|0110155|0110155|0110155|0110155|0110155  \
0  |0110154|0110154|0110154|0110154|0110154|01101...
1  |0110153|0110153|0110153|0110153|0110153|01101...
2  |0110152|0110152|0110152|0110152|0110152|01101...
3  |0110151|0110151|0110151|0110151|0110151|01101...
4  |0110150|0110150|0110150|0110150|0110150|01101...

   Unnamed: 4  Unnamed: 5  600  608  Unnamed: 8  Unnamed: 9  ...  296  450  \
0         NaN         NaN  500  540         NaN         NaN  ...  248  380
1         NaN         NaN  500  506         NaN         NaN  ...  212  384
2         NaN         NaN  600  579         NaN         NaN  ...  249  473
3         NaN         NaN  500  477         NaN         NaN  ...  240  379
4         NaN         NaN  500  467         NaN         NaN  ...  207  369

   1.1  149  12  3  134    147     7    140
0    1  119   3  4  112  129.0  10.0  119.0
1    1  115   6  5  104   97.0  11.0   86.0
2    1  126   4  5  117  123.0  11.0  112.0
3    1  120   3  6  111  120.0   5.0  115.0
4    1  130   6  4  120   77.0   4.0   73.0

[5 rows x 21 columns]

--- SECTIONS DATA ---

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12966 entries, 0 to 12965
Data columns (total 9 columns):
 #   Column                                                       Non-Null Count  Dtype
---  ------                                                       --------------  -----
 0   010100001                                                    12966 non-null  int64
 1   1                                                            12966 non-null  int64
 2   01. БЛАГОЕВГРАД                                              12966 non-null  object
 3   2676                                                         12966 non-null  int64
 4   гр.Банско                                                    12966 non-null  object
 5   гр. БАНСКО СОУ  НЕОФИТ РИЛСКИ , УЛ.  ТОДОР АЛЕКСАНДРОВ  №9Б  12930 non-null  object
 6   0                                                            12966 non-null  int64
 7   0.1                                                          12966 non-null  int64
 8   1.1                                                          12966 non-null  int64
dtypes: int64(6), object(3)
memory usage: 911.8+ KB
None
   010100001  1  01. БЛАГОЕВГРАД  2676  гр.Банско  \
0   10100002  1  01. БЛАГОЕВГРАД  2676  гр.Банско
1   10100003  1  01. БЛАГОЕВГРАД  2676  гр.Банско
2   10100004  1  01. БЛАГОЕВГРАД  2676  гр.Банско
3   10100005  1  01. БЛАГОЕВГРАД  2676  гр.Банско
4   10100006  1  01. БЛАГОЕВГРАД  2676  гр.Банско

  гр. БАНСКО СОУ  НЕОФИТ РИЛСКИ , УЛ.  ТОДОР АЛЕКСАНДРОВ  №9Б  0  0.1  1.1
0  гр. БАНСКО ПЛТГ  Н. ВАПЦАРОВ  (ГОРСКИ ТЕХНИКУМ...           0    0    1
1  гр. БАНСКО ПЛТГ  Н. ВАПЦАРОВ  (ГОРСКИ ТЕХНИКУМ...           0    0    1
2  гр. БАНСКО КЛУБ НА ПЕНСИОНЕРА, ул.  ЦАР СИМЕОН...           0    0    1
3  гр. БАНСКО ЧИТАЛИЩЕ  НИКОЛА ВАПЦАРОВ , ПЛ.  НИ...           0    0    1
4  гр. БАНСКО НАЧАЛНО УЧИЛИЩЕ  СВ. ПАИСИЙ ХИЛИНДА...           0    0    1

--- VOTES DATA ---

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12975 entries, 0 to 12974
Columns: 127 entries, 26 to 1.22
dtypes: int64(127)
memory usage: 12.6 MB
None
   26  010100001  1  1.1  22  7  15  2  0  0.1  ...  0.41  0.42  31  0.43  \
0  26   10100002  1    1  16  5  11  2  3    0  ...     0     0  31     0
1  26   10100003  1    1  13  4   9  2  0    0  ...     0     0  31     0
2  26   10100004  1    1   8  6   2  2  1    0  ...     0     1  31     0
3  26   10100005  1    1  11  4   7  2  1    1  ...     0     0  31     0
4  26   10100006  1    1  11  6   5  2  0    0  ...     1     0  31     0

   0.44  0.45  32  1.21  0.46  1.22
0     0     0  32     0     0     0
1     0     0  32     0     0     0
2     0     0  32     0     0     0
3     0     0  32     0     0     0
4     0     0  32     0     0     0

[5 rows x 127 columns]

In [18]:
# Load the dataset again with some manual cleaning
protocols_df = pd.read_csv( r'C:\stasi\SoftUni_DATA_SCIENCE\FINAL_PROJECT\DATA\РЕЗУЛТАТИ ИЗБОРИ 2024\export\Актуализирана база данни - НС\protocols_09.06.2024.csv', delimiter=';', engine='python', on_bad_lines='skip')

# Drop the problematic columns (e.g., columns with unexpected formats or entirely NaN values)
protocols_df_cleaned = protocols_df.drop(columns=['Unnamed: 4', 'Unnamed: 5', 'Unnamed: 8', 'Unnamed: 9'])

# Check if the column with the repeated patterns can be split into multiple columns or if it should be removed
if '|' in protocols_df_cleaned.columns[3]:
    # If this is the case, you might want to drop or process it
    protocols_df_cleaned = protocols_df_cleaned.drop(columns=[protocols_df_cleaned.columns[3]])

# Display the cleaned DataFrame info and first few rows
print(protocols_df_cleaned.info())
print(protocols_df_cleaned.head())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12975 entries, 0 to 12974
Data columns (total 16 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   26         12975 non-null  int64
 1   010100001  12975 non-null  int64
 2   1          12975 non-null  int64
 3   600        12975 non-null  int64
 4   608        12975 non-null  int64
 5   4          12975 non-null  int64
 6   296        12975 non-null  int64
 7   450        12975 non-null  int64
 8   1.1        12975 non-null  int64
 9   149        12975 non-null  int64
 10  12         12975 non-null  int64
 11  3          12975 non-null  int64
 12  134        12975 non-null  int64
 13  147        9600 non-null   float64
 14  7          9600 non-null   float64
 15  140        9600 non-null   float64
dtypes: float64(3), int64(13)
memory usage: 1.6 MB
None
   26  010100001  1  600  608  4  296  450  1.1  149  12  3  134    147     7  \
0  26   10100002  1  500  540  3  248  380    1  119   3  4  112  129.0  10.0
1  26   10100003  1  500  506  0  212  384    1  115   6  5  104   97.0  11.0
2  26   10100004  1  600  579  0  249  473    1  126   4  5  117  123.0  11.0
3  26   10100005  1  500  477  2  240  379    1  120   3  6  111  120.0   5.0
4  26   10100006  1  500  467  0  207  369    1  130   6  4  120   77.0   4.0

     140
0  119.0
1   86.0
2  112.0
3  115.0
4   73.0